[project]
name = "sim-anillos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beanie>=1.29.0,<2.0.0",
    "motor>=3.7.0",
    "fastapi[standard]>=0.115.11",
    "loguru>=0.7.3",
    "matplotlib>=3.10.1",
    "pandas>=2.2.3",
    "plotly>=6.0.0",
    "torch>=2.7.0",
    "uuid7-standard>=1.0.0",
]

[tool.uv.workspace]
members = [
    "frontend",
]

[tool.uv.sources]
torch = { index = "pytorch-cu126" }

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true
